### ISSUE TITLE
Create the "Choose your location" section

### ISSUE THREAD

**Issue by stephendawsondev** [jdhernandezS1/Summer_Hackaton#28] opened 2023-07-14 16:12 UTC
In the "Select" your city section, there are 4 image cards. They may have functionality that flips the card to describe it. Designs found here: https://www.figma.com/file/33kwyBIsqkOHgrO7CeUuoi/Summer-coding

**Comment by stephendawsondev** [comment] 2023-07-14 16:15
This is related to the #15 and #16 issues, so whoever takes this one could take them all. I recommend using something like Unsplash or https://www.pickpik.com/ to source images.

**Comment by CarlaBuongiorno** [comment] 2023-07-14 20:25
Closing as this is a duplicate of #26

**Closed as completed by CarlaBuongiorno** 2023-07-14 20:25 UTC
Labels: duplicate, front
